{
 "title": "Thermal cam and AQI dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Thermal cam", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Thermal camera heat map (Celcius)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(thermalcam_heatmap_frameSummary_v2_pixels_bucket{application=\"publishHeatMap\"}, \"le\", \"$1\", \"le\", \"(.*)(000.0)\") ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "AQI, temp, humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "AQI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "round(voc_aqi_index{application=\"voc-prometheus-publisher\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raw gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "voc_raw_gas{application=\"voc-prometheus-publisher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "description": "Percent relative humidity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "voc_rel_humidity{application=\"voc-prometheus-publisher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "voc_temp_c{application=\"voc-prometheus-publisher\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}