global:
  scrape_interval: 10s
  evaluation_interval: 20s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "publish-heat-map"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 20s
    static_configs:
      - targets: ["host.docker.internal:8080"]
